# Generated by Django 4.1.6 on 2023-05-25 12:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.FloatField(max_length=50)),
                ('description', models.CharField(default='Lorem, ipsum dolor sit amet consectetur adipisicing elit. Eum laudantium quia nisi optio laborum ut quisquam? Laboriosam labore fugit voluptatibus dicta, praesentium iste placeat, fuga modi dignissimos nesciunt nemo eligendi?', max_length=500)),
                ('image', models.ImageField(upload_to='menu_images')),
                ('category', models.CharField(choices=[('DRINKS', 'Drinks'), ('DESSERTS', 'Desserts'), ('BURGER', 'Burger'), ('PIZZA', 'Pizza'), ('SOUP', 'Soup')], max_length=50)),
                ('rate', models.CharField(choices=[('⭐', '⭐'), ('⭐', '⭐⭐'), ('⭐', '⭐⭐⭐'), ('⭐', '⭐⭐⭐⭐'), ('⭐', '⭐⭐⭐⭐⭐')], default='in_review', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.item')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('ordered_date', models.DateField()),
                ('ordered', models.BooleanField(default=False)),
                ('items', models.ManyToManyField(to='customer.orderitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
