# Generated by Django 4.1.6 on 2023-05-25 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('DRINKS', 'Drinks'), ('DESSERTS', 'Desserts'), ('BURGER', 'Burger'), ('PIZZA', 'Pizza')], max_length=50),
        ),
    ]
