# Generated by Django 4.1.6 on 2023-06-15 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_alter_item_category_alter_item_price_alter_item_rate_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='item',
            new_name='product',
        ),
    ]
