# Generated by Django 4.1.6 on 2023-06-19 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_usercheckout_remove_orderitem_item_delete_order_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercheckout',
            name='price',
        ),
        migrations.AddField(
            model_name='usercheckout',
            name='totalcash',
            field=models.IntegerField(default='0', max_length=200),
            preserve_default=False,
        ),
    ]
