# Generated by Django 4.1.6 on 2023-06-19 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_remove_usercheckout_price_usercheckout_totalcash'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercheckout',
            name='user_identifier',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usercheckout',
            name='ordered_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='usercheckout',
            name='telephone',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='usercheckout',
            name='totalcash',
            field=models.IntegerField(),
        ),
    ]
