# Generated by Django 4.1.6 on 2023-06-19 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0007_usercheckout_user_identifier_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercheckout',
            name='payment_method',
            field=models.CharField(choices=[('credit_card', 'Credit Card'), ('paypal', 'PayPal'), ('ussd', 'USSD'), ('cash', 'Cash'), ('bank_transfer', 'Bank Transfer')], max_length=100),
        ),
        migrations.AlterField(
            model_name='usercheckout',
            name='user_identifier',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
