# Generated by Django 4.1.6 on 2023-06-27 10:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customer', '0008_alter_usercheckout_payment_method_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercheckout',
            name='user_identifier',
        ),
        migrations.AddField(
            model_name='usercheckout',
            name='deliveryfee',
            field=models.PositiveIntegerField(default=500),
        ),
        migrations.AddField(
            model_name='usercheckout',
            name='fullname',
            field=models.CharField(default='user', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usercheckout',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
