# Generated by Django 4.1.6 on 2024-02-27 10:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customer', '0009_remove_usercheckout_user_identifier_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('DRINKS', 'Drinks'), ('DESSERTS', 'Desserts'), ('BURGER', 'Burger'), ('PIZZA', 'Pizza')], max_length=50),
        ),
        migrations.CreateModel(
            name='placeOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100)),
                ('deliveryfee', models.PositiveIntegerField(default=500)),
                ('totalcash', models.IntegerField()),
                ('email', models.CharField(max_length=100)),
                ('telephone', models.IntegerField()),
                ('shipping_address', models.CharField(max_length=100)),
                ('payment_method', models.CharField(choices=[('credit_card', 'Credit Card'), ('paypal', 'PayPal'), ('ussd', 'USSD'), ('cash', 'Cash'), ('bank_transfer', 'Bank Transfer')], max_length=100)),
                ('ordered_date', models.DateTimeField(auto_now_add=True)),
                ('ordered', models.BooleanField(default=False)),
                ('items', models.ManyToManyField(to='customer.cart')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
