# Generated by Django 4.1.6 on 2024-02-28 14:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customer', '0011_order_ordereditem_delete_placeorder'),
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='order',
            name='delivery_fee',
        ),
        migrations.RemoveField(
            model_name='order',
            name='total_cash',
        ),
        migrations.AddField(
            model_name='order',
            name='deliveryfee',
            field=models.PositiveIntegerField(default=500),
        ),
        migrations.AddField(
            model_name='order',
            name='email',
            field=models.CharField(default='abc@gmail.com', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='fullname',
            field=models.CharField(default='name', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='items',
            field=models.ManyToManyField(to='customer.cart'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('credit_card', 'Credit Card'), ('paypal', 'PayPal'), ('ussd', 'USSD'), ('cash', 'Cash'), ('bank_transfer', 'Bank Transfer')], default='cash', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_address',
            field=models.CharField(default='address', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='telephone',
            field=models.IntegerField(default=123456),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='totalcash',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='usercheckout',
            name='email',
            field=models.CharField(default='abcd@gmail.com', max_length=100),
        ),
        migrations.AlterField(
            model_name='usercheckout',
            name='totalcash',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='OrderedItem',
        ),
        migrations.AddField(
            model_name='items',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordered_items', to='customer.order'),
        ),
    ]
