# Generated by Django 4.1.6 on 2024-02-28 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0012_items_remove_order_delivery_fee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
