# Generated by Django 4.1.6 on 2024-07-03 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0014_alter_order_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Items',
            new_name='Ordered_item',
        ),
    ]
